
######################## default configuration ####################
baseURL = "https://devday4w.com/"
title = "Dev Day 4 Women"
enableRobotsTXT = true
DefaultContentLanguage = "es"

theme = "dd4w"
# post pagination
paginate = "8"

# Este es el tag normal de analytics
# googleAnalytics = "G-HV96ZN2N60"
# Este es el de google tag manager
googleAnalytics = "GTM-MXJFH7W"

[taxonomies]
tag = "tags"
category = "categories"
speaker = "speakers"

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "/plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
link = "/plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css"


# JS Plugins
[[params.plugins.js]]
link = "/plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "/plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
link="https://unpkg.com/bootstrap-table@1.18.0/dist/bootstrap-table.min.js"
[[params.plugins.js]]
link="https://kit.fontawesome.com/a6f10b653b.js"

############################## navigation ###############################
[menu]

  #[[menu.main]]
  #name = "Agenda"
  #URL = "/agenda/"
  #weight = 1


  #[[menu.main]]
  #identifier = "program"
  #name = "Sesiones"
  #URL = "/sessions/noviembre-2021/"
  #weight = 1

  #[[menu.main]]
   # identifier = "program1"
    #name = "Programa Abril 2021"
    #URL = "/sessions"
    #parent = "program"
    #weight = 1

  #[[menu.main]]
   # identifier = "program2"
    #name = "Programa Noviembre 2021"
    #url = "/programa-nov"
    #parent = "program"
    #weight = 2

  #[[menu.main]]
  #name = "Nominaciones"
  #URL = "/nominaciones"
  #weight = 2

  [[menu.main]]
  name = "Sesiones anteriores"
  URL = "/sessions"
  weight = 1


  [[menu.main]]
  name = "Reconocimientos SG4W"
  URL = "/reconocimientos"
  weight = 3

  [[menu.main]]
  name = "Speakers"
  URL = "/speakers/archive"
  weight = 2

  #[[menu.main]]
  #name = "Agenda"
  #URL = "/agenda"
  #weight = 1

  
  #[[menu.main]]
  #name = "Networking"
  #URL = "/networking"
  #weight = 4

  #[[menu.main]]
  #name = "Kit Virtual"
  #URL = "/kitvirtual"
  #weight = 5

  [[menu.main]]
  name = "FAQ"
  URL = "/faq"
  weight = 6



#################### default parameters ################################
[params]
logo = "/images/logo-monochrome.svg"
home = "Home"

# Meta data
description = """Dev Day for Women es un evento virtual para mujeres involucradas en el desarrollo de software."""
images = ["/images/blog/dd4w.jpg"]
twitter_user = "RevistaSG"
email = "eventos@sg.com.mx"
author = "Software Guru"

start_date = "2021-04-14T11:00-05:00"
end_date = "2021-04-15T19:00-05:00"



disclaimer = """DevDay 4 Women es otro fantástico evento de Software Guru."""


# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = false
label = "Live"
link = "/live/"


############################# social icon ############################

[[params.social]]
icon = "tf-ion-social-twitter"
link = "https://twitter.com/sg4women"

[[params.social]]
icon = "tf-ion-social-facebook"
link = "https://www.facebook.com/groups/SG4Women"

[[params.social]]
icon = "fas fa-envelope"
link = "mailto:eventos@sg.com.mx"

[[params.social]]
icon = "fa-brands fa-slack"
link = "https://join.slack.com/t/sg4women/shared_invite/zt-ukzdodky-nUaFePrq73NEIC3y61M_PQ"

[[params.footer_previous]]
name = "Acerca de"
link = "https://sg.com.mx/sg4w"

[[params.footer_previous]]
name = "?Quién organiza¿"
link = "/team/"

[[params.footer_previous]]
name = "Código de Conducta"
link = "/coc/"

[[params.footer_previous]]
name = "DD4W Abril 2021"
link = "/sessions/abril-2021/"

[[params.footer_previous]]
name = "DD4W Noviembre 2021"
link = "/sessions/noviembre-2021/"

[[params.footer_previous]]
name = "DD4W Abril 2022"
link = "/sessions/abril-2022/"

[[params.footer_sponsorship]] 
name = "Prospectus"
link = "/files/DevDay4women virtual Prospectus 2022 H2.pdf"


[[params.footer_resources]] 
name = "Email"
link = "mailto:eventos@sg.com.mx"







