
######################## default configuration ####################
baseURL = "https://devday4w.com/"
title = "Dev Day 4 Women"
enableRobotsTXT = true
DefaultContentLanguage = "es"

theme = "dd4w"
# post pagination
paginate = "8"

# Este es el tag normal de analytics
# googleAnalytics = "G-HV96ZN2N60"
# Este es el de google tag manager
[services.googleAnalytics]
  id = "GTM-MXJFH7W"

[taxonomies]
tag = "tags"
category = "categories"
speaker = "speakers"
nominaciones = "nominaciones"

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "/plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
link = "/plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css"


# JS Plugins
[[params.plugins.js]]
link = "/plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "/plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
link="https://unpkg.com/bootstrap-table@1.18.0/dist/bootstrap-table.min.js"
# [[params.plugins.js]]
# link="https://kit.fontawesome.com/a6f10b653b.js"
[[params.plugins.css]]
link = "/plugins/fontawesome.css"
[[params.plugins.css]]
link = "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
[[params.plugins.css]]
link = "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"

############################## navigation ###############################
[menu]

[ languages.es]


  [[languages.es.menu.main]]
  name = "PONENTES"
  URL = "/speakers/archive"
  weight = 4

  [[languages.es.menu.main]]
  name = "BLOG"
  URL = "blog"
  weight = 6

  [[languages.es.menu.main]]
    name = "Vacantes"
    URL = "/vacantes"
    weight = 6

  [[languages.es.menu.main]]
    name = "FAQs"
    URL = "/faq"
    weight = 7

  [languages.ia]

  [[languages.ia.menu.main]]
    name = "PONENTES"
    URL = "/ia/speakers"
    weight = 2

  [[languages.ia.menu.main]]
    name = "Agenda"
    URL = "/ia/agenda"
    weight = 1

  [[languages.ia.menu.main]]
    name = "Registro"
    URL = "/ia/registro"
    weight = 3

    [[languages.ia.menu.main]]
    name = "FAQ"
    URL = "/ia/faq"
    weight = 4


#################### default parameters ################################
[params]
logo = "/images/logo-monochrome.svg"
home = "Home"

# Meta data
description = """Dev Day for Women es un evento virtual para mujeres involucradas en el desarrollo de software."""
images = ["/images/card-2025-dd4w.jpg"]
twitter_user = "RevistaSG"
email = "eventos@sg.com.mx"
author = "Software Guru"

start_date = "2021-04-14T11:00-05:00"
end_date = "2021-04-15T19:00-05:00"

disclaimer = """DevDay 4 Women es otro fantástico evento de Software Guru."""

google_analytics = "GTM-MXJFH7W"


# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "Registro al evento"
link = "/registro"


############################# social icon ############################

[[params.social]]
icon = "bi bi-twitter-x"
link = "https://twitter.com/Code4DEI"

[[params.social]]
icon = "tf-ion-social-facebook"
link = "https://www.facebook.com/code4dei"

[[params.social]]
icon = "tf-ion-social-instagram"
link = "https://www.instagram.com/code4dei"


[[params.social]]
icon = "bi bi-envelope-at-fill"
link = "mailto:eventos@sg.com.mx"

[[params.social]]
icon = "bi bi-slack"
link = "https://join.slack.com/t/sg4women/shared_invite/zt-ukzdodky-nUaFePrq73NEIC3y61M_PQ"

[[params.footer_resources]]
name = "Acerca de"
link = "https://sg.com.mx/sg4w"

[[params.footer_resources]]
name = "?Quién organiza¿"
link = "/team/"

[[params.footer_resources]]
name = "Comité de Mujeres Code 4 DEI"
link = "https://code4dei.com/comite/"

[[params.footer_resources]]
name = "Media Kit"
link = "/media-kit/"

[[params.footer_resources]]
name = "Código de Conducta"
link = "/coc/"

[[params.footer_previous]]
name = "Speakers"
link = "/speakers/archive"

[[params.footer_previous]]
name = "Sesiones"
link = "/sessions/"

[[params.footer_previous]]
name = "Reconocimientos CODE 4 DEI 2023"
link = "/reconocimientos"

[[params.footer_previous]]
name = "Reconocimientos CODE 4 DEI 2024"
link = "/reconocimientos-2024"

[[params.footer_contact_us]] 
name = "Email"
link = "mailto:eventos@sg.com.mx"

[[params.footer_contact_us]] 
name = "Quiero patrocinar"
link = "/files/dev_day_4_women_monterrey_prospectus_2025.pdf"